---
title: "results"
output: html_document
date: "2025-02-05"
---

```{r libraries, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(ggplot2)
library(psych)
library(FSA)
library(tidyr)

```

# big teams as a phenomenon

```{r}
ggplot(aes(x = pubdate, colour = n_author), data = dat) +
  geom_histogram()+
  theme_minimal()

```


```{r}
ggplot(aes(x = pubdate, y = citation), data = dat) +
  geom_point()+
  theme_minimal()

```


```{r}

ggplot(aes(x = n_author, y = citation), data = dat) +
  geom_point()+
  theme_minimal()


```




```{r}

dat|> filter(n_author> 15)|>
  ggplot(aes(citation, factor(author_group_ten)))+
  geom_violin()+
  theme_minimal()+
  coord_cartesian(xlim = c(0, 1000))

```

```{r}

dat|> filter(n_author> 15)|>
  ggplot(aes(citation, factor(author_group_five)))+
  geom_violin()+
  theme_minimal()+
  coord_cartesian(xlim = c(0, 1000))

```

```{r}

dat|> filter(n_author> 20)|>
  ggplot(aes(citation, factor(author_group_fifteen)))+
  geom_violin()+
  theme_minimal()+
  coord_cartesian(xlim = c(0, 1000))

```

```{r}
corr<- cor(dat$n_author, dat$citation, method = "spearman", use = "complete.obs")
print(corr)
test_corr<-cor.test(dat$n_author, dat$citation, method = "spearman", use = "complete.obs")
corr2<- cor(dat$n_author, dat$citation_2y, method = "spearman", use = "complete.obs")
print(corr2)
```


# Citation

```{r}

dat |>
  group_by(author_group_five) |>
  summarise(
    median_citations = median(citation, na.rm = TRUE),
    count = n()
  ) |>
  ggplot(aes(x = author_group_five, y = median_citations)) +
  geom_col(fill = "steelblue") +
  geom_text(aes(label = count, y = median_citations + 2), size = 3, angle = 90) +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 

```

```{r}
dat |>
  group_by(author_group_ten) |>
  summarise(
    median_citations = median(citation, na.rm = TRUE),
    count = n()
  ) |>
  ggplot(aes(x = author_group_ten, y = median_citations)) +
  geom_col(fill = "steelblue") +
  geom_text(aes(label = count, y = median_citations + 2), size = 3, angle = 90) +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

```
```{r}
dat |>
  group_by(author_group_fifteen) |>
  summarise(
    median_citations = median(citation, na.rm = TRUE),
    count = n()
  ) |>
  ggplot(aes(x = author_group_fifteen, y = median_citations)) +
  geom_col(fill = "steelblue") +
  geom_text(aes(label = count, y = median_citations + 2), size = 3, angle = 90) +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

```

```{r}
counts_five <- dat |> 
  group_by(author_group_five) |> 
  summarise(count = n(), .groups = "drop")

dat |>
  ggplot(aes(x = author_group_five, y = citation)) +
  geom_boxplot(outlier.shape = NA, fill = "lightblue") +
  stat_summary(fun = mean, geom = "point", color = "red", size = 2) +
  geom_text(
    data = counts_five,
    aes(x = author_group_five, y = 402, label = count),  # put labels above boxes
    inherit.aes = FALSE,
    size = 3,
    angle = 90
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  coord_cartesian(ylim = c(0, 410))
```

```{r}
counts_ten <- dat |> 
  group_by(author_group_ten) |> 
  summarise(count = n(), .groups = "drop")

dat |>
  ggplot(aes(x = author_group_ten, y = citation)) +
  geom_boxplot(outlier.shape = NA, fill = "lightblue") +
  stat_summary(fun = mean, geom = "point", color = "red", size = 2) +
  geom_text(
    data = counts_ten,
    aes(x = author_group_ten, y = 402, label = count),  # put labels above boxes
    inherit.aes = FALSE,
    size = 3,
    angle = 90
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  coord_cartesian(ylim = c(0, 410))

```


```{r}
counts_fif <- dat |> 
  group_by(author_group_fifteen) |> 
  summarise(count = n(), .groups = "drop")

dat |>
  ggplot(aes(x = author_group_fifteen, y = citation)) +
  geom_boxplot(outlier.shape = NA, fill = "lightblue") +
  stat_summary(fun = mean, geom = "point", color = "red", size = 2) +
  geom_text(
    data = counts_fif,
    aes(x = author_group_fifteen, y = 402, label = count),  # put labels above boxes
    inherit.aes = FALSE,
    size = 3,
    angle = 90
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  coord_cartesian(ylim = c(0, 410))

```

```{r}
dat |>
  group_by(author_group_five) |>
  ggplot(aes(x = author_group_five, y = citation_2y)) +
  geom_boxplot(outlier.shape = NA, fill = "lightblue") +
  stat_summary(
    fun = mean, geom = "point", color = "red", size = 2
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  coord_cartesian(ylim = c(0, 250))

```

```{r}
dat |>
  group_by(author_group_ten) |>
  ggplot(aes(x = author_group_ten, y = citation_2y)) +
  geom_boxplot(outlier.shape = NA, fill = "lightblue") +
  stat_summary(
    fun = mean, geom = "point", color = "red", size = 2
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  coord_cartesian(ylim = c(0, 250))

```

```{r}
dat |>
  group_by(author_group_fifteen) |>
  ggplot(aes(x = author_group_fifteen, y = citation_2y)) +
  geom_boxplot(outlier.shape = NA, fill = "lightblue") +
  stat_summary(
    fun = mean, geom = "point", color = "red", size = 2
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  coord_cartesian(ylim = c(0, 250))

```

```{r}
des<- dat|>
  group_by(author_group_five)|>
  summarise(n=n(),
            across(c(citation), list( mean = mean, sd = sd, median = median, IQR= IQR), .names = "{.col}_{.fn}"))


print(des)

```

```{r}
des_ten<- dat|>
  group_by(author_group_ten)|>
  summarise(n=n(),
            across(c(citation), list( mean = mean, sd = sd, median = median, IQR= IQR), .names = "{.col}_{.fn}"))


print(des_ten)

```

```{r}
des_fif<- dat|>
  group_by(author_group_fifteen)|>
  summarise(n=n(),
            across(c(citation), list( mean = mean, sd = sd, median = median, IQR= IQR), .names = "{.col}_{.fn}"))


print(des_fif)

```


```{r}
des2y<- dat |>
  group_by(author_group_five)|>
  summarise(n=n(),
            across(c(citation_2y), list( mean = ~mean(.x, na.rm = TRUE), sd = ~sd(.x, na.rm = TRUE), median = ~median(.x, na.rm = TRUE), IQR=  ~IQR(.x, na.rm = TRUE)), .names = "{.col}_{.fn}"))


des2y

```


```{r}
des2y|>ggplot(aes(x = author_group_five, y=citation_2y_mean))+
  geom_col(color = "darkblue")+
  geom_errorbar(aes(ymin=citation_2y_mean-citation_2y_sd, ymax=citation_2y_mean+citation_2y_sd), width=0.4, colour="orange", alpha=0.9, linewidth=1.3)+
  theme_classic()
```


```{r}
des2y_ten<- dat |>
  group_by(author_group_ten)|>
  summarise(n=n(),
            across(c(citation_2y), list( mean = mean, sd = sd, median = median, IQR=  ~IQR(.x, na.rm = TRUE)), .names = "{.col}_{.fn}"))


des2y_ten

```

```{r}
des2y_fif<- dat |>
  group_by(author_group_fifteen)|>
  summarise(n=n(),
            across(c(citation_2y), list( mean = mean, sd = sd, median = median, IQR=  ~IQR(.x, na.rm = TRUE)), .names = "{.col}_{.fn}"))


des2y_fif

```


```{r}
kruskat_five<- kruskal.test(citation ~ author_group_five, data = dat)
kruskat_five

```


```{r}
duun_five<- dunnTest(citation ~ author_group_five, data = dat, method = "bh")
duun_five$res[order(-duun_five$res$Z),]


```


```{r}


# Extract group names
dunn_summary_five <- duun_five$res |>
  filter(P.adj < 0.05) |>
  mutate(winner = ifelse(Z > 0, sub(" - .*", "", Comparison),
                         sub(".* - ", "", Comparison)),
         loser  = ifelse(Z > 0, sub(".* - ", "", Comparison),
                         sub(" - .*", "", Comparison)))

# Count wins
group_scores_five <- dunn_summary_five |>
  count(winner, name = "wins")

# Optionally count losses too
group_losses_five <- dunn_summary_five |>
  count(loser, name = "losses")

# Combine
ranking_five <- full_join(group_scores_five, group_losses_five, by = c("winner" = "loser")) |>
  rename(group = winner) |>
  mutate(wins = replace_na(wins, 0),
         losses = replace_na(losses, 0),
         net_score = wins - losses) |>
  arrange(desc(net_score))

ranking_five
```


```{r}
kruskat_ten<- kruskal.test(citation ~ author_group_ten, data = dat)
kruskat_ten
```


```{r}
duun_ten<- dunnTest(citation ~ author_group_ten, data = dat, method = "bh")
duun_ten$res[order(-duun_ten$res$Z),]
```


```{r}
dunn_summary_ten <- duun_ten$res |>
  filter(P.adj < 0.05) |>
  mutate(winner = ifelse(Z > 0, sub(" - .*", "", Comparison),
                         sub(".* - ", "", Comparison)),
         loser  = ifelse(Z > 0, sub(".* - ", "", Comparison),
                         sub(" - .*", "", Comparison)))


group_scores_ten <- dunn_summary_ten |>
  count(winner, name = "wins")


group_losses_ten <- dunn_summary_ten |>
  count(loser, name = "losses")


ranking_ten <- full_join(group_scores_ten, group_losses_ten, by = c("winner" = "loser")) |>
  rename(group = winner) |>
  mutate(wins = replace_na(wins, 0),
         losses = replace_na(losses, 0),
         net_score = wins - losses) |>
  arrange(desc(net_score))

ranking_ten

```


```{r}
kruskat_fif<- kruskal.test(citation ~ author_group_fifteen, data = dat)
kruskat_fif
```

```{r}
duun_fif<- dunnTest(citation ~ author_group_fifteen, data = dat, method = "bh")

duun_fif$res[order(-duun_fif$res$Z),]
```


```{r}
dunn_summary_fif <- duun_fif$res |>
  filter(P.adj < 0.05) |>
  mutate(winner = ifelse(Z > 0, sub(" - .*", "", Comparison),
                         sub(".* - ", "", Comparison)),
         loser  = ifelse(Z > 0, sub(".* - ", "", Comparison),
                         sub(" - .*", "", Comparison)))


group_scores_fif <- dunn_summary_fif |>
  count(winner, name = "wins")


group_losses_fif <- dunn_summary_fif |>
  count(loser, name = "losses")


ranking_fif <- full_join(group_scores_fif, group_losses_fif, by = c("winner" = "loser")) |>
  rename(group = winner) |>
  mutate(wins = replace_na(wins, 0),
         losses = replace_na(losses, 0),
         net_score = wins - losses) |>
  arrange(desc(net_score))

ranking_fif

```



```{r}
percent0cite_five <- dat |>
  group_by(author_group_five) |>
  summarise(cite0 = sum(citation == 0) / n())|>
  arrange(desc(cite0))

percent0cite_five
```


```{r}
percent0cite_ten <- dat |>
  group_by(author_group_ten) |>
  summarise(cite0 = sum(citation == 0) / n())|>
  arrange(desc(cite0))

percent0cite_ten
```


```{r}
percent0cite_fif <- dat |>
  group_by(author_group_fifteen) |>
  summarise(cite0 = sum(citation == 0) / n())|>
  arrange(desc(cite0))

percent0cite_fif
```



```{r}
year2011 <- dat |> 
  filter(pubdate >= "2011-01-01" & pubdate < "2012-01-01") |> 
  group_by(author_group_ten) |> 
  summarise(
    median_citations = median(citation, na.rm = TRUE),
    count = n()
  ) |> 
  pivot_longer(cols = c(median_citations, count), names_to = "metric", values_to = "value")

ggplot(year2011, aes(x = author_group_ten, y = value, color = metric, group = metric)) +
  geom_line() +
  geom_point() +
  theme_minimal()


year2011
```



```{r}
year2020 <- dat |> 
  filter(pubdate >= "2020-01-01" & pubdate < "2021-01-01") |> 
  group_by(author_group_ten) |> 
  summarise(
    median_citations = median(citation, na.rm = TRUE),
    count = n()
  ) |> 
  pivot_longer(cols = c(median_citations, count), names_to = "metric", values_to = "value")

ggplot(year2011, aes(x = author_group_ten, y = value, color = metric, group = metric)) +
  geom_line() +
  geom_point() +
  theme_minimal()

year2020

```



```{r}
year1990 <- dat |> 
  filter(pubdate >= "1990-01-01" & pubdate < "1991-01-01") |> 
  group_by(author_group_ten) |> 
  summarise(
    median_citations = median(citation, na.rm = TRUE),
    count = n()
  ) |> 
  pivot_longer(cols = c(median_citations, count), names_to = "metric", values_to = "value")

ggplot(year2011, aes(x = author_group_ten, y = value, color = metric, group = metric)) +
  geom_line() +
  geom_point() +
  theme_minimal()

year1990

```


```{r}
duun_fif2<- dunnTest(citation_2y ~ author_group_fifteen, data = dat, method = "bh")

duun_fif2$res[order(-duun_fif2$res$Z),]
```


```{r}
dunn_summary_fif2 <- duun_fif2$res |>
  filter(P.adj < 0.05) |>
  mutate(winner = ifelse(Z > 0, sub(" - .*", "", Comparison),
                         sub(".* - ", "", Comparison)),
         loser  = ifelse(Z > 0, sub(".* - ", "", Comparison),
                         sub(" - .*", "", Comparison)))


group_scores_fif2 <- dunn_summary_fif2 |>
  count(winner, name = "wins")


group_losses_fif2 <- dunn_summary_fif2 |>
  count(loser, name = "losses")


ranking_fif2 <- full_join(group_scores_fif2, group_losses_fif2, by = c("winner" = "loser")) |>
  rename(group = winner) |>
  mutate(wins = replace_na(wins, 0),
         losses = replace_na(losses, 0),
         net_score = wins - losses) |>
  arrange(desc(net_score))

ranking_fif2

```



```{r}
duun_ten2<- dunnTest(citation_2y ~ author_group_ten, data = dat, method = "bh")
duun_ten2$res[order(-duun_ten2$res$Z),]
```


```{r}
 XXXdunn_summary_ten2 <- duun_ten2$res |>
  filter(P.adj < 0.05) |>
  mutate(winner = ifelse(Z > 0, sub(" - .*", "", Comparison),
                         sub(".* - ", "", Comparison)),
         loser  = ifelse(Z > 0, sub(".* - ", "", Comparison),
                         sub(" - .*", "", Comparison)))


group_scores_ten2 <- dunn_summary_ten2 |>
  count(winner, name = "wins")


group_losses_ten2 <- dunn_summary_ten2 |>
  count(loser, name = "losses")


ranking_ten2 <- full_join(group_scores_ten2, group_losses_ten2, by = c("winner" = "loser")) |>
  rename(group = winner) |>
  mutate(wins = replace_na(wins, 0),
         losses = replace_na(losses, 0),
         net_score = wins - losses) |>
  arrange(desc(net_score))

ranking_ten2

```



```{r}
duun_five2<- dunnTest(citation_2y ~ author_group_five, data = dat, method = "bh")
duun_five2$res[order(-duun_five2$res$Z),]
```


```{r}
library(see)
dat|>group_by(author_group_ten)|>
   ggplot(aes(x = author_group_ten, y= citation_2y, fill = author_group_ten))+
   geom_violinhalf()+
  theme_classic()+
  ylim(0, 10)
```


```{r}
dat |>
  group_by(author_group_five) |>
  summarise(
    `70%` = quantile(citation_2y, 0.70, na.rm = TRUE),
    `80%` = quantile(citation_2y, 0.80, na.rm = TRUE),
    `90%` = quantile(citation_2y, 0.90, na.rm = TRUE),
    `99%` = quantile(citation_2y, 0.99, na.rm = TRUE),
    `99.99%` = quantile(citation_2y, 0.9999, na.rm = TRUE),
    .groups = "drop"
  )
```


```{r}
dat|> filter(!is.na(author_group_five))|>group_by(author_group_five)|> summarise(value= quantile(citation_2y, c(.7, .8, .90, .99, .9999)))|> mutate(percentile = as.factor(c(.7, .8,.9,.99, .9999)))|>
  ggplot(aes(x=author_group_five, y = value, color = percentile))+
  geom_line() +
  geom_point(size= 2)+
  theme_classic()+
  labs(x= "Author group", y= "Second-year citation")
```

```{r}
library(tibble)
probs <- c(`70%`=.70, `80%`=.80, `90%`=.90, `99%`=.99, `99.99%`=.9999)

plot_dat <- dat %>%
  filter(!is.na(author_group_five)) %>%
  group_by(author_group_five) %>%
  summarise(
    enframe(quantile(citation_2y, probs = probs, na.rm = TRUE),
            name = "percentile", value = "value"),
    .groups = "drop"
  ) %>%
  mutate(percentile = factor(percentile, levels = names(probs)))

ggplot(plot_dat, aes(x = author_group_five, y = value,
                     color = percentile, group = percentile)) +
  geom_line() +
  geom_point(size = 2) +
  theme_classic() +
  labs(x = "Author group", y = "Second-year citation", color = "Percentile")
```



```{r}
dat|>filter(n_author<20)|>summarise(value= quantile(citation_2y, c(.7, .8, .90, .99)))|> mutate(percentile = as.factor(c(.7, .8,.9,.99)))
```


```{r}
dat|>filter(n_author<20)|>summarise(value= quantile(corr_citation, c(.7, .8, .90, .99)))|> mutate(percentile = as.factor(c(.7, .8,.9,.99)))
```


```{r}
dat|>mutate(author_bin = if_else(n_author<20, "<20 authors", "above 20 authors"))|> group_by(author_bin)|>summarise(value= quantile(citation, c(.7, .8, .90, .99)))|> mutate(percentile = as.factor(c(.7, .8,.9,.99)))
```



