---
title: "missing info"
output: html_document
date: "2025-08-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```


```{r}
missing_years<- dat|>mutate(pubyear = format(pubdate, "%Y"))|> group_by(pubyear)|> summarise(sum(is.na(n_author)))

ggplot(aes(x = as.integer(pubyear), y = `sum(is.na(n_author))`), data= missing_years)+
  geom_line(color = "blue")+
  geom_point(color = "red")
```

```{r}
missing_ref <- dat|>mutate(pubyear = format(pubdate, "%Y"))|> group_by(pubyear)|> summarise(miss_ref = sum(ref == ""))

ggplot(aes(x = as.integer(pubyear), y = miss_ref), data= missing_ref)+
  geom_line(color = "blue")+
  geom_point(color = "red")
```

```{r}
missing_issn <- dat|>mutate(pubyear = format(pubdate, "%Y"))|> group_by(pubyear)|> summarise(miss_issn = sum(is.na(issn)))
ggplot(aes(x = as.integer(pubyear), y = miss_issn), data= missing_issn)+
  geom_line(color = "blue")+
  geom_point(color = "red")
```



```{r}
missing_years<- dat|>mutate(pubyear = format(pubdate, "%Y"))|> group_by(pubyear)|> summarise(remiss_author= sum(is.na(n_author))/n())

ggplot(aes(x = as.integer(pubyear), y = remiss_author), data= missing_years)+
  geom_line(color = "blue")+
  geom_point(color = "red")


```

```{r}
missing_ref <- dat|>mutate(pubyear = format(pubdate, "%Y"))|> group_by(pubyear)|> summarise(remiss_ref = sum(ref == "")/n())

ggplot(aes(x = as.integer(pubyear), y = remiss_ref), data= missing_ref)+
  geom_line(color = "blue")+
  geom_point(color = "red")

```

```{r}
p1 <- dat_sjr |>
  mutate(source = "dat_sjr") |>
  select(SJR, source)

p2 <- SJR |>
  filter(!is.na(SJR), SJR != "") |>
  mutate(SJR = gsub(",", ".", SJR),
         SJR = as.numeric(SJR),
         source = "SJR_full") |>
  select(SJR, source)

combined <- bind_rows(p1, p2)

ggplot(combined, aes(x = SJR, fill = source)) +
  geom_density(alpha = 0.4) +
  xlim(c(0, 25)) +
  theme_classic()
```





