---
title: "Journal ranking"
---


```{r libraries, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(ggplot2)
library(psych)
library(stats)
library(tidyr)
library(readr)
library(stringr)
library(here)
```

```{r}
dat<- readRDS(here("data","consolidate_data_openalex.rds"))
SJR<- read_delim(here("data","scimagojr 2024.csv"), delim = ";")
```


```{r}

length(unique(SJR$Issn))
SJR<- SJR|>distinct(Issn, .keep_all = TRUE)

SJR<- SJR|> separate_rows(Issn, sep = "\\s*,\\s*", convert = TRUE)|>rename(stanissn = Issn)

dat_sjr <- dat |>
  mutate(stanissn = gsub("-", "", issn))


dat_sjr<- dat_sjr|> left_join(SJR |> select(stanissn, SJR), by = "stanissn")

dat_sjr<- dat_sjr|> 
  filter(!is.na(SJR), SJR != "") |> mutate(SJR = gsub(",", ".", SJR), SJR=as.numeric(SJR))
 
```

```{r}
saveRDS(dat_sjr, here("data","consolidate_journal_data.rds"))
```


# correlation

```{r}
test_corr<-cor.test(dat_sjr$n_author, dat_sjr$SJR, method = "spearman", use = "complete.obs")
test_corr
```

```{r}
dat_sjr |>
  group_by(author_group_five) |>
  ggplot(aes(x = author_group_five, y = SJR)) +
  geom_boxplot(outlier.shape = NA, fill = "lightblue") +
  stat_summary(
    fun = mean, geom = "point", color = "red", size = 2
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  coord_cartesian(ylim = c(0, 15))+
  labs(x = "Author groups", y= "SJR")
```

```{r}
dat_sjr |>
  group_by(author_group_ten) |>
  ggplot(aes(x = author_group_ten, y = SJR)) +
  geom_boxplot(outlier.shape = NA, fill = "lightblue") +
  stat_summary(
    fun = mean, geom = "point", color = "red", size = 2
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  coord_cartesian(ylim = c(0, 15))+
  labs(x = "Author groups", y= "SJR")
```

```{r}
dat_sjr |>
  group_by(author_group_fifteen) |>
  ggplot(aes(x = author_group_fifteen, y = SJR)) +
  geom_boxplot(outlier.shape = NA, fill = "lightblue") +
  stat_summary(
    fun = mean, geom = "point", color = "red", size = 2
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  coord_cartesian(ylim = c(0, 15))+
  labs(x = "Author groups", y= "SJR")
```


# descriptive analysis

```{r}

summary_table_sjr<- dat_sjr|>filter(!is.na(SJR))|>summarise(n=n(),
            across(c(SJR), list( mean = mean, sd = sd, median = median, max = max, min = min), .names = "{.col}_{.fn}"))

summary_table_sjr
```


```{r}
sjrdes<- dat_sjr|>
  group_by(author_group_five)|>
  summarise(n=n(),
            across(c(SJR), list( mean = ~mean(.x, na.rm = TRUE),
        sd = ~sd(.x, na.rm = TRUE),
        median = ~median(.x, na.rm = TRUE),
        IQR = ~IQR(.x, na.rm = TRUE)), .names = "{.col}_{.fn}"))

sjrdes

```

```{r}
sjrdes10<- dat_sjr|>
  group_by(author_group_ten)|>
  summarise(n=n(),
            across(c(SJR), list( mean = ~mean(.x, na.rm = TRUE),
        sd = ~sd(.x, na.rm = TRUE),
        median = ~median(.x, na.rm = TRUE),
        IQR = ~IQR(.x, na.rm = TRUE)), .names = "{.col}_{.fn}"))

sjrdes10

```

```{r}
sjrdes15<- dat_sjr|>
  group_by(author_group_fifteen)|>
  summarise(n=n(),
            across(c(SJR), list( mean = ~mean(.x, na.rm = TRUE),
        sd = ~sd(.x, na.rm = TRUE),
        median = ~median(.x, na.rm = TRUE),
        IQR = ~IQR(.x, na.rm = TRUE)), .names = "{.col}_{.fn}"))

sjrdes15

```


# percentile check

```{r}
dat_sjr|>mutate(author_bin = if_else(n_author<20, "<20 authors", "above 20 authors"))|> group_by(author_bin)|>summarise(value= quantile(SJR, c(.7, .8, .90, .99)))|> mutate(percentile = as.factor(c(.7, .8,.9,.99)))
```


```{r}
mm_sjr<- dat_sjr|> filter(n_author>=20)|> summarise(mean = round(mean(SJR), 2), median = median(SJR))

y <- mm_sjr$median

com_perc_sjr<- dat_sjr |>
  mutate(author_bin = if_else(n_author < 20, "<20 authors", ">=20 authors")) |>
  group_by(author_bin) |>
  summarise(
    n = sum(!is.na(SJR)),
    percentile = 100 * mean(SJR <= y, na.rm = TRUE)
  )
```


```{r}
dat_sjr|>filter(n_author<20)|>group_by(author_group_five)|> summarise(value= quantile(SJR, c(.7, .8, .90, .99)))|> mutate(percentile = as.factor(c(.7, .8,.9,.99)))|>
  ggplot(aes(x=author_group_five, y = value, color = percentile))+
  geom_point(size= 2)+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  labs(x= "Author group", y= "SJR")+
  scale_color_manual(values = c("#2f4b7c", "#d45087", "#f95d6a", "#F0A430"))+
  geom_hline(aes(yintercept = mm_sjr$median, linetype = "Median"), color = "darkred", size = 1 )+
  geom_hline(aes(yintercept = mm_sjr$mean, linetype = "Mean"), color = "darkred", size = 1.2)+
  scale_linetype_manual(name = "Large team values", values = c("dotted","solid"))
```


```{r}
dat_sjr|>filter(n_author<20)|>group_by(author_group_ten)|> summarise(value= quantile(SJR, c(.7, .8, .90, .99)))|> mutate(percentile = as.factor(c(.7, .8,.9,.99)))|>
  ggplot(aes(x=author_group_ten, y = value, color = percentile))+
  geom_point(size= 2)+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  labs(x= "Author group", y= "SJR")+
  scale_color_manual(values = c("#2f4b7c", "#d45087", "#f95d6a", "#F0A430"))+
  geom_hline(aes(yintercept = mm_sjr$median, linetype = "Median"), color = "darkred", size = 1 )+
  geom_hline(aes(yintercept = mm_sjr$mean, linetype = "Mean"), color = "darkred", size = 1.2)+
  scale_linetype_manual(name = "Large team values", values = c("dotted","solid"))
```


```{r}
dat_sjr|>filter(n_author<20)|>group_by(author_group_fifteen)|> summarise(value= quantile(SJR, c(.7, .8, .90, .99)))|> mutate(percentile = as.factor(c(.7, .8,.9,.99)))|>
  ggplot(aes(x=author_group_fifteen, y = value, color = percentile))+
  geom_point(size= 2)+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  labs(x= "Author group", y= "SJR")+
  scale_color_manual(values = c("#2f4b7c", "#d45087", "#f95d6a", "#F0A430"))+
  geom_hline(aes(yintercept = mm_sjr$median, linetype = "Median"), color = "darkred", size = 1 )+
  geom_hline(aes(yintercept = mm_sjr$mean, linetype = "Mean"), color = "darkred", size = 1.2)+
  scale_linetype_manual(name = "Large team values", values = c("dotted","solid"))
```


